title: PMLE
description: gClouds Tech Documents
theme: just-the-docs
domain: g-clouds.github.io
baseurl: "/ml"
url: "https://docs.gclouds.co.uk"

aux_links:
  "gClouds Web Site":
    - "//www.gclouds.co.uk"
aux_links_new_tab: true

heading_anchors: true
enable_copy_code_button: true
nav_enabled: true

logo: "/assets/images/gclouds.png"
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.9.1"

footer_content: "Copyright Â© 2024  |  <a href='https://www.gclouds.co.uk'>gClouds</a> . All rights reserved."